# Generated by Django 2.2.6 on 2020-10-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='quote',
            field=models.TextField(default=None),
        ),
    ]
